@host=anypoint.mulesoft.com/mocking/api/v1/links/0ff5ac86-bcc8-466b-b18d-31aef2b6fd56

### Accept GET from a different Origin
GET https://{{host}}/data/nocors
Accept: application/json
Origin: localhost

### Accept GET from a different Origin
GET https://{{host}}/data/get-cors
Accept: application/json
Origin: http://localhost
###

### Accept GET from a different Origin
POST https://{{host}}/data/all-cors
Accept: application/json
Origin: http://localhost

### Accept GET from a different Origin
OPTIONS https://{{host}}/data/all-cors
Origin: http://localhost
Accept: application/json